name: Close stale PRs

on:
  schedule:
    # Schedule the workflow to run every day at 00:00 UTC
    - cron: '* * * * *'

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code repository
      - uses: actions/checkout@v2
      
      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run the Python script to close stale PRs
      - name: Close stale PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python stale.py
