name: Stale

on:
  schedule:
    - cron: '* * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - name: Close stale pull requests
      uses: actions/stale@v3
      with:
        days: 14
        exclude_labels: "do not close, reviewed"
        include_drafts: false
        message: "This pull request has been closed due to inactivity. If you'd like to continue working on it, please open a new pull request."
