name: Close stale PRs

on:
  schedule:
    # Schedule the workflow to run every day at 00:00 UTC
    - cron: '* * * * *'

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code repository
      - uses: actions/checkout@v2
      
      # Install Python and dependencies
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install PyGithub==1.55
      
      # Run the Python script to close stale PRs
      - name: Close stale PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          import os
          from datetime import datetime, timedelta
          from github import Github
          
          # Get the current time and the time 3 weeks ago
          now = datetime.now()
          weeks_ago = now - timedelta(weeks=3)
          
          # Authenticate with the GitHub API
          g = Github(os.getenv('GITHUB_TOKEN'))
          repo = g.get_repo('krishi0408/cd-pipeline-sample')
          
          # Get all open PRs for the repository
          prs = repo.get_pulls(state='open')
          
          # Loop through each PR and close it if it's stale
          for pr in prs:
              last_updated = pr.updated_at
              if last_updated < weeks_ago:
                  pr.create_issue_comment("This pull request has been automatically closed because it hasn't been updated in 3 weeks.")
                  pr.edit(state='closed')
          EOF

